language: php

php:
  - 5.6

before_script:
  - cp .env.travis .env
  - mysql -e 'create database travis_testing;'
  - composer self-update
  - composer install --no-interaction
  - touch database/badger_testing.sqlite

script:
  - vendor/bin/phpunit